retryable-exceptions : TrendyolDBException,TrendyolKafkaException,TrendyolRestClientException,DeserializationException,InvalidDataAccessResourceUsageException,DataIntegrityViolationException
retry-max-attempt : 5