spring:
  application:
    name: '@project.name@'
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    include: pdf, postgresql
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.xml
