spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: "jdbc:postgresql://10.85.122.1:5001/int_seller_commission_invoice"
    username: int_seller_commission_invoice_appuser
    password: sr5@uZD*5!s5NT+g
    hikari:
      pool-name: international-commission-invoice-pool
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      connection-timeout: 3000
      maximum-pool-size: 9
  jpa:
    database: postgresql
    properties:
      hibernate:
        jdbc:
          fetch_size: 2000
