spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/int_seller_commission_invoice
    username: int_seller_commission_invoice_appuser
    password: 1234567890
  jpa:
    properties:
      jdbc.batch_size: 50
      hibernate:
        order_inserts: true
        order_updates: true
        show_sql: false
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml