spring:
  application:
    name: '@project.name@'
    description: '@project.description@'
    termsOfService: https://www.trendyol.com/kullanim_kosullari.html
  profiles:
    active: test
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/mem/testdb;INIT=RUNSCRIPT FROM 'classpath:data.sql';DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    username: sa
    password:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
  sql:
    init:
      mode: always

springdoc:
  api-docs:
    path: /api-docs
distance:
  scale: 4

earth:
  radiues: 6371.13