spring:
  application:
    name: '@project.name@'
    description: '@project.description@'
    termsOfService: https://www.trendyol.com/kullanim_kosullari.html
  profiles:
    active: local
    include: kafka, postgresql
springdoc.api-docs.path: /api-docs