version: '3.1'
services:
  postgresql:
    image: "kartoza/postgis:9.6-2.4"
    restart: unless-stopped
    hostname: postgresql
    domainname: postgresql
    environment:
      POSTGRES_USER: int_seller_commission_invoice_appuser
      POSTGRES_PASS: 1234567890
      POSTGRES_DBNAME: int_seller_commission_invoice
      ALLOW_IP_RANGE: 0.0.0.0/0
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var
    networks:
      - sellerfinance-net

  zookeeper-server:
    image: bitnami/zookeeper:latest
    restart: unless-stopped
    networks:
      - sellerfinance-net
    container_name: zookeeper-server
    hostname: zookeeper-server
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - ./zookeeper-server:/bitnami/zookeeper
    ports:
      - "2181:2181"

  kafka-server-1:
    image: bitnami/kafka:2.3.0
    container_name: kafka-server-1
    restart: unless-stopped
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_BROKER_ID=1
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_DELETE_TOPIC_ENABLE=true
      - KAFKA_DEFAULT_REPLICATION_FACTOR=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_NUM_PARTITIONS=2
      - KAFKA_PORT_NUMBER=9092
      - KAFKA_LISTENERS=PLAINTEXT://kafka-server-1:9092,PLAINTEXT_HOST://:29092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-server-1:9092,PLAINTEXT_HOST://localhost:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
    ports:
      - "9092:9092"
      - "29092:29092"
    networks:
      - sellerfinance-net
    depends_on:
      - zookeeper-server
    volumes:
      - ./kafka-server-1:/bitnami/kafka

networks:
  sellerfinance-net:
    driver: bridge

volumes:
  postgresql:
